Project_Dj_hnzlru/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls', namespace='home')),
    path('authorization/', include('authorization.urls', namespace='authorization')),
    path('patients/', include('patients.urls', namespace='patients')),

    # TODO: сделать редирект на 404
    # Перенаправление всех несуществующих URL на главную страницу
    path('<path:invalid_path>', RedirectView.as_view(url='/', permanent=False)),
]

authorization/urls.py
from django.urls import path, include

# При использовании from . import views внутри модуля или пакета означает, что вы
# импортируете модуль views из текущего пакета или из текущей директории. Символ .
# в данном случае представляет текущий пакет или текущую директорию.
from . import views

# from .views import AboutView, ContactsView

app_name = 'authorization'

urlpatterns = [
    # главная страница (вызываем через ф-цию)
    # path('', IndexView.as_view(), name='home'),
    path('login/', views.index, name='login'),
    path('logout/', views.logout, name='logout'),

    # path('about', AboutView.as_view(), name='about'),

    # path('contacts', ContactsView.as_view(), name='contacts'),
]

home/urls.py
from django.urls import path, include
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', HomeListView.as_view(), name='index'),
    path('client_questions/', ClientQuestions.as_view(), name='client_questions'),
    path('client_results/', ClientResults.as_view(), name='client_results'),

    path('send_email_health_check/', send_email_health_check, name='send_email_health_check'),
    path('notification/<code>', notification, name='notification'),
]

home/models.py
from django.db import models

#
# # UserAnswer
# class ClientQuestionsAnswer(models.Model):
#     session_key = models.CharField(max_length=32, null=True, blank=True)
#     question_text = models.CharField(max_length=255)
#     answer_text = models.CharField(max_length=255)

home/views.py
from datetime import datetime, timedelta
from typing import Final

from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, TemplateView

from Project_Dj_hnzlru import settings
from home.forms import *
from home.notification_codes import NOTIFICATION_CODES
from patients.models import COPDPatients


# TODO: сделать в дальнейшем выводы из БД!!!
class HomeListView(ListView):
    model = COPDPatients
    context_object_name = 'COPDPatients'
    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        portfolio_numbers = [
            'gallery-1.jpg',
            'gallery-2.jpg',
            'gallery-3.jpg',
            'gallery-4.jpg',
            'gallery-5.jpg',
            'gallery-6.jpg',
        ]

        context['portfolio_numbers'] = portfolio_numbers
        return context


class ClientQuestions(TemplateView):
    CURRENT_DATE: Final = datetime.now().date()
    template_name = 'home/client_questions.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # получаем номер запроса который должен прийти и в зависимости от
        # запроса рендерим форму
        if self.request.GET.get('quest_number') is None:
            quest_number = 1
        else:
            quest_number = int(self.request.GET.get('quest_number'))

        context['form'] = self._get_forms(str(quest_number))
        context['quest_number'] = quest_number
        context['questions'] = QUESTIONS

        return context

    def post(self, request, *args, **kwargs):
        question_handlers = {
            1: self._handle_quest1,
            2: self._handle_quest2,
            3: self._handle_quest3,
            4: self._handle_quest4,
            5: self._handle_quest5,
            6: self._handle_quest6,
            7: self._handle_quest7,
            8: self._handle_quest8,
            9: self._handle_quest9,
            10: self._handle_quest10,
            11: self._handle_quest11,
            12: self._handle_quest12,
        }

        if 'user_answers' not in request.session:
            request.session['user_answers'] = {}

        for quest_number, handler in question_handlers.items():
            if quest_number == int(request.POST['quest_number']):  # 1, 2,... n
                handler(request, quest_number)
                break

        # **

        # Перенаправление на следующий вопрос
        next_quest_number = int(quest_number) + 1

        if next_quest_number > len(QUESTIONS):
            # конец опроса, переход на результат
            return HttpResponseRedirect(reverse('home:client_results'))
        else:
            # идем дальше по вопросам
            return HttpResponseRedirect(reverse(
                'home:client_questions') + f'?quest_number={next_quest_number}')

    # **

    # Возвращает класс формы в зависимости от номера вопроса
    def _get_forms(self, form_number):
        form_list = {
            '1': ClientQuestion1Form(),
            '2': ClientQuestion2Form(),
            '3': ClientQuestion3Form(),
            '4': ClientQuestion4Form(),
            '5': ClientQuestion5Form(),
            '6': ClientQuestion6Form(),
            '7': ClientQuestion7Form(),
            '8': ClientQuestion8Form(),
            '9': ClientQuestion9Form(),
            '10': ClientQuestion10Form(),
            '11': ClientQuestion11Form(),
            '12': ClientQuestion12Form(),
        }

        return form_list.get(form_number, forms.Form)

    # **

    # рассчет ИМТ (веса)
    def _handle_quest1(self, request, quest_number):
        height = request.POST['form1_height']
        weight = request.POST['form1_weight']

        # рассчитываем индекс массы тела (пример: 185/88 => 88/1,85^2=25.7)
        # True: bmi > 30 and False: bmi <= 30
        height_in_meters = int(height) / 100  # Преобразуем высоту в метры
        body_mass_index = int(weight) / (height_in_meters ** 2)
        bmi = round(body_mass_index, 1)  # один знак после запятой

        # session
        request.session['user_answers'][quest_number] = f'{bmi}/{height}/{weight}'
        request.session.save()

    # рассчет АТ (давления: blood pressure)
    def _handle_quest2(self, request, quest_number):
        up_pressure = int(request.POST['form2_max'])
        down_pressure = int(request.POST['form2_min'])

        request.session['user_answers'][quest_number] = f'{up_pressure}/{down_pressure}'
        request.session.save()

    # холестирин
    def _handle_quest3(self, request, quest_number):
        cholesterol = float(request.POST['form3_cholesterol'])

        request.session['user_answers'][quest_number] = cholesterol
        request.session.save()

    # глюкоза
    def _handle_quest4(self, request, quest_number):
        glucose = float(request.POST['form4_glucose'])

        request.session['user_answers'][quest_number] = glucose
        request.session.save()

    # онкология
    def _handle_quest5(self, request, quest_number):
        self._last_visit_calculate(request, quest_number, 5)

    # ишемия
    def _handle_quest6(self, request, quest_number):
        self._last_visit_calculate(request, quest_number, 6)

    # сосуды головного мозга
    def _handle_quest7(self, request, quest_number):
        self._last_visit_calculate(request, quest_number, 7)

    # заболевания почек
    def _handle_quest8(self, request, quest_number):
        self._last_visit_calculate(request, quest_number, 8)

    # заболевания печени
    def _handle_quest9(self, request, quest_number):
        self._last_visit_calculate(request, quest_number, 9)

    # заболевания суставов
    def _handle_quest10(self, request, quest_number):
        self._last_visit_calculate(request, quest_number, 10)

    # Заболевания щитовидной железы
    def _handle_quest11(self, request, quest_number):
        self._last_visit_calculate(request, quest_number, 11)

    # Заболевания позвоночника
    def _handle_quest12(self, request, quest_number):
        self._last_visit_calculate(request, quest_number, 12)

    # **

    def _last_visit_calculate(self, request, quest_number, form_number):
        last_visit_str = request.POST[f'form{form_number}_date_of_the_last_visit']
        last_visit = datetime.strptime(last_visit_str, '%Y-%m-%d').date()
        time_difference_in_days = abs((self.CURRENT_DATE - last_visit).days)

        request.session['user_answers'][quest_number] = time_difference_in_days
        request.session.save()


class ClientResults(TemplateView):
    ALERT_OK: Final = '[Ок]'
    ALERT_PROBLEM: Final = '[Есть проблемы]'
    CURRENT_DATE: Final = datetime.now().date()

    results = {}

    template_name = 'home/client_results.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        self._processing_results(self.request.session['user_answers'])

        context['form_feedback'] = ClientFeedback()
        context['user_answers'] = self.results
        context['questions'] = QUESTIONS

        return context

    def _processing_results(self, user_answers):
        self.results.clear()

        check_processings = {
            1: self._check_processing1,
            2: self._check_processing2,
            3: self._check_processing3,
            4: self._check_processing4,
            5: self._check_processing5,
            6: self._check_processing6,
            7: self._check_processing7,
            8: self._check_processing8,
            9: self._check_processing9,
            10: self._check_processing10,
            11: self._check_processing11,
            12: self._check_processing12,
        }

        for key_answer, val_answer in user_answers.items():
            for key_question, val_question in QUESTIONS:
                if int(key_answer) == int(key_question):
                    # TODO: рбочий код - не ктрогать пока что !!!
                    # print(val_question, val_answer)
                    # self.results[val_question] = val_answer

                    for number, processing in check_processings.items():
                        if number == int(key_answer):
                            self.results[val_question] = processing(val_answer)
                            break

    # **

    def _check_processing1(self, value):
        BMI_MAX = 30.0
        val_str = str(value)
        bmi, height, weight = val_str.split('/')

        bmi = float(bmi)
        height = int(height)
        weight = int(weight)

        if bmi >= BMI_MAX:
            return f'индекс {bmi}, при росте {height}, весе {weight} {self.ALERT_PROBLEM}'
        else:
            return f'индекс {bmi}, при росте {height}, весе {weight} {self.ALERT_OK}'

    def _check_processing2(self, value):
        BP_UP_MAX = 140
        BP_DOWN_MIN = 90

        val_str = str(value)
        up_pressure_str, down_pressure_str = val_str.split('/')

        up_pressure = int(up_pressure_str)
        down_pressure = int(down_pressure_str)

        if up_pressure >= BP_UP_MAX or down_pressure >= BP_DOWN_MIN:
            return f'{val_str} {self.ALERT_PROBLEM}'
        else:
            return f'{val_str} {self.ALERT_OK}'

    def _check_processing3(self, value):
        CHOLESTEROL_MAX = 5.2
        val = float(value)

        if val > CHOLESTEROL_MAX:
            return f'{val} {self.ALERT_PROBLEM}'
        else:
            return f'{val} {self.ALERT_OK}'

    def _check_processing4(self, value):
        GLUCOSE_MAX = 6.2
        val = float(value)

        if val > GLUCOSE_MAX:
            return f'{val} {self.ALERT_PROBLEM}'
        else:
            return f'{val} {self.ALERT_OK}'

    def _check_processing5(self, value):
        return self._last_visit_calculate(value)

    def _check_processing6(self, value):
        return self._last_visit_calculate(value)

home/templates/home/client_results.html
{% extends 'home/layout.html' %}
{% block title %}Результаты анкеты{% endblock %}

{% block content %}

  <!-- Page Content -->
  <section id="page-content">
    <div class="container">
      <div class="row">
        <div class="content col-lg-12">

          <!-- feedback: begin -->
          {% include 'home/template_feedback.html' %}
          <!-- feedback: end -->

          <div class="line"></div>

          <!-- result: begin -->
          <div class="card">
            <div class="card-body">
              <h3 class="mb-5">Результаты <small>(оценки здоровья)</small></h3>

              <div class="form-group col-md-6">
                {% for key, val in user_answers.items %}
                  <p>
                    {{ key }}:
                    <span class="client__processing-status badge badge-pill">
                    {{ val }}
                  </span>
                  </p>
                {% endfor %}
              </div>
            </div>
          </div>
          <!-- result: end -->

        </div>

        <!-- Sidebar-->
        <div class="sidebar col-lg-3">
          <div class="sidebar-menu">
            {% if quest_number > 1 %}
              <label>Пройдено</label>
              <ul>
                {% for number, text in questions %}
                  {% if quest_number > number %}
                    <li {% if number < quest_number %}style="text-decoration: line-through;"{% endif %}>
                      {{ text }}
                    </li>
                  {% endif %}
                {% endfor %}
              </ul>
            {% endif %}

            {% for number, text in questions %}
              {% if quest_number == number %}
                <label>Текущий вопрос: </label>
                <ul>
                  <li style="color: #0333e8; font-weight: bold;">
                    {{ text }}
                  </li>
                </ul>
              {% endif %}
            {% endfor %}
          </div>
        </div>
        <!-- end: sidebar-->
      </div>
    </div>
  </section>
  <!-- end: Page Content -->


  <!-- ** -->


  <script>
    let statusElements = document.querySelectorAll('.client__processing-status');

    statusElements.forEach(function(statusElement) {
      let statusText = statusElement.innerText;

      if (statusText.includes('[Ок]')) {
        statusElement.classList.add('bg-success');
        statusElement.classList.remove('bg-danger');
      } else {
        statusElement.classList.add('bg-danger');
        statusElement.classList.remove('bg-success');
      }
    });
  </script>

{% endblock content %}

home/templates/home/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="ХОБЛ" content="Липецкая городская поликлиника №2" />
  <meta name="ХОБЛ" content="ХОБЛ - пациенты">
  <link rel="icon" type="image/png" href="{% static 'home/images/logo.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- Document title -->
  <title>{% block title %}{% endblock %}</title>

  <!-- Stylesheets & Fonts -->
  <link href="{% static 'public/css/plugins.css' %}" rel="stylesheet">
  <link href="{% static 'public/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'home/css/home.css' %}" rel="stylesheet">
</head>

<body class="side-panel side-panel-static">

    <!-- Side Panel -->
    <div id="side-panel" class="text-center dark">
        <div id="close-panel">
            <i class="fa fa-times"></i>
        </div>

        <div class="side-panel-wrap">
            <div class="logo">
                <a href="{% url 'home:index' %}">
                  <img src="{% static 'home/images/logo.png' %}" style="width:80px; height:100px;">
                </a>
            </div>
            <hr class="space">

            <!--Navigation-->
            <div id="mainMenu" class="menu-onclick menu-vertical">
                <div class="container">
                    {% include 'home/template_menu.html' %}
                </div>
            </div>
            <!--end: Navigation-->


            <hr class="space">
            <hr class="space">
            <!--social icons-->
            <div class="social-icons social-icons-colored text-center">
                <ul>
{#                    <li class="social-facebook"><a href="#"><i class="fab fa-facebook-f"></i></a></li>#}
{#                    <li class="social-twitter"><a href="#"><i class="fab fa-twitter"></i></a></li>#}
{#                    <li class="social-google"><a href="#"><i class="fab fa-google-plus-g"></i></a></li>#}
{#                    <li class="social-pinterest"><a href="#"><i class="fab fa-pinterest"></i></a></li>#}

                    <li class="social-vimeo"><a href="https://vk.com/club130729996" target="_blank"><i class="fab fa-vk"></i></a></li>
                </ul>
            </div>
            <!--end: social icons-->

            <!--copyright text-->
            <p class="small">© 2023 ГУЗ Липецкая городская поликлиника №2</p>
            <!--end: copyright text-->
        </div>

    </div>
    <!-- end: Side Panel -->

    <!-- Body Inner -->
    <div class="body-inner">

        <!-- Header -->
        <header id="header" class="d-block d-md-none dark" data-transparent="true">

            <div class="header-inner">
                <div class="container">
                    <!--Header Extras-->
                    <div class="header-extras">
                        <ul>
                            <li>
                                <!--side panel-->
                                <a id="side-panel-trigger" href="#" class="toggle-item" data-target="body" data-class="side-panel-active">
                                    <i class="fa fa-bars"></i>
                                    <i class="fa fa-times"></i>
                                </a>
                                <!--end: side panel-->
                            </li>
                        </ul>
                    </div>
                    <!--end: Header Extras-->

                </div>
            </div>
        </header>
        <!-- end: Header -->

        <!-- Page Content -->
        {% block content %}{% endblock %}
        <!-- end: Page Content -->

        <!-- Footer -->
        <footer id="footer">
            <div class="footer-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-5">
                            <div class="widget">
                                <div class="widget-title">ХОБЛ / ХНЗЛ</div>
                                <p class="mb-5">Данные для регистра ХОБЛ<br> Все права защищены. Copyright © 2023</p>
                                <a href="http://lip2.ru"
                                   class="btn btn-inverted"
                                   target="_blank"
                                >Перейти на сайт поликлиники №2</a>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="row">
                                <div class="col-lg-3">
                                    <div class="widget">
                                        <div class="widget-title">Главная</div>
                                        <ul class="list">
                                            <li><a href="{% url 'home:client_questions' %}">Оценка здоровья</a></li>
                                            <li><a href="{% url 'authorization:login' %}">Для персонала</a></li>
                                        </ul>
                                    </div>
                                </div>

                                <!--
                                <div class="col-lg-3">
                                    <div class="widget">
                                        <div class="widget-title">Информация</div>
                                        <ul class="list">
                                            <li><a href="#">1</a></li>
                                            <li><a href="#">2</a></li>
                                            <li><a href="#">3</a></li>
                                            <li><a href="#">4</a></li>
                                        </ul>
                                    </div>
                                </div>
                                -->

                                <!--
                                <div class="col-lg-3">
                                    <div class="widget">
                                        <div class="widget-title">Pages</div>
                                        <ul class="list">
                                            <li><a href="#">Portfolio</a></li>
                                            <li><a href="#">Blog</a></li>
                                            <li><a href="#">Shop</a></li>
                                        </ul>
                                    </div>
                                </div>
                                -->

                                <!--
                                <div class="col-lg-3">
                                    <div class="widget">
                                        <div class="widget-title">Support</div>
                                        <ul class="list">
                                            <li><a href="#">Help Desk</a></li>
                                            <li><a href="#">Documentation</a></li>
                                            <li><a href="#">Contact Us</a></li>
                                        </ul>
                                    </div>
                                </div>
                                -->
                            </div>
                        </div>


                    </div>
                </div>
            </div>
            <div class="copyright-content">
                <div class="container">
                    <div class="copyright-text text-center">&copy; 2021 POLO - Responsive Multi-Purpose HTML5 Template. All Rights Reserved.<a href="https://www.inspiro-media.com" target="_blank" rel="noopener"> INSPIRO</a> </div>
                </div>
            </div>
        </footer>
        <!-- end: Footer -->

    </div>
    <!-- end: Body Inner -->

    <!-- Scroll top -->
    <a id="scrollTop"><i class="icon-chevron-up"></i><i class="icon-chevron-up"></i></a>

    <!--Plugins-->
    <script src="{% static 'public/js/jquery.js' %}"></script>
    <script src="{% static 'public/js/plugins.js' %}"></script>

    <!--Template functions-->
    <script src="{% static 'public/js/functions.js' %}"></script>

    <!--Feedback mask for phone-->
    <script type='text/javascript'
            src="{% static 'home/js/imask-feedback.js' %}"
            id='e-sticky-js'>
    </script>
</body>

</html>

home/templates/home/notification.html
{% extends 'home/layout.html' %}
{% block title %}Результаты анкеты{% endblock %}

{% block content %}

  <!-- 500 PAGE -->
  <section class="p-b-200">
    <div class="container">
      <div class="row p-t-200">
        <div class="col-lg-6">
          <div class="page-error-404 text-center">{{ icon_html|safe }}</div>
        </div>
        <div class="col-lg-6">
          <div class="text-start">
            <h1 class="text-medium"> {{ message }} </h1>
            <p class="lead">{{ sub_message }}</p>

            <div class="seperator m-t-20 m-b-20"></div>

            <a href="{% url 'home:index' %}"
              class="btn btn-primary"
              type="button"
            >Главная
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end:  500 PAGE -->

{% endblock content %}

home/templates/home/template_feedback.html
{% load static %}


<div class="card">
  <div class="card-body">
    <form
      class="form-validate"
      action="{% url 'home:send_email_health_check' %}"
      method="POST"
      onsubmit="return checkClientFeedbackFormData();"
    >
      {% csrf_token %}

      <h3>{{ form_feedback.title}}</h3>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            {{ form_feedback.name }}
          </div>
          <div class="form-group">
            {{ form_feedback.surname }}
          </div>
          <div class="form-group">
            {{ form_feedback.phone }}
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            {{ form_feedback.message }}
          </div>
        </div>

        <div class="form-group">
          <label class="custom-control-label" for={{ form_feedback.terms_conditions.id_for_label }}>
            {{ form_feedback.terms_conditions }}
            Даю согласие на обработку
            <a href="{% static 'docs/pers_dannyh.doc' %}"
               target="_blank"
               download
            >
              персональных данных
            </a>
          </label>
        </div>

        <!-- передаем ответы пользователя в форму -->
        <input
          type="hidden"
          name="user_answers"
          value="{% for key, value in user_answers.items %}
            {{ key }}:{{ value }}{% if not forloop.last %},{% endif %}{% endfor %}"
        >

        <div class="col-md-12">
          <div class="form-group">
            <button type="submit" class="btn btn-primary">Отправить</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>


<!-- ** -->


<!-- валидация инпутов перед отправкой формы -->
<script>
  function checkNameField(name) {
    // Проверка на русские буквы в имени
    let russianLettersPattern = /^[А-Яа-яЁё]+$/;

    if (name.value.length < 2 || name.value.length > 20) {
      name.style.border = '2px solid #fbca19';
      return false;
    } else {
      name.style.border = '1px solid #ccc';
    }

    if (!russianLettersPattern.test(name.value)) {
      name.style.border = '2px solid #fbca19';
      return false;
    } else {
      name.style.border = '1px solid #ccc';
    }

    return true;
  }

  function checkPhoneField(phone) {
    let inputValue = phone.value;

    /**
     * Паттерн для проверки формата:
     *
     * +7-123-456-78-90
     * +7(123)-456-78-90
     * +7-1234567890
     * +71234567890
     * 71234567890
     * 7(123)456-78-90
     */
    let phonePattern = /^\+?[7][-\(]?\d{3}\)?-?\d{3}-?\d{2}-?\d{2}$/;

    if (!phonePattern.test(inputValue)) {
      phone.style.border = '2px solid #fbca19';
      return false;
    } else {
      phone.style.border = '1px solid #ccc';
    }

    return true;
  }

  function checkClientFeedbackFormData() {
    let name = document.getElementById('client_feedback_name');
    let surname = document.getElementById('client_feedback_surname');
    let phone = document.getElementById('client_feedback_phone');

    if (checkNameField(name) === true
      && checkNameField(surname) === true
      && checkPhoneField(phone) === true) {
      return true;
    }

    return false;
  }
</script>


<!-- ** -->


<!-- маска для номера телефона -->
<script>
  window.onload = function() {
    initializeMaskedInput('client_feedback_phone');
  };

  function initializeMaskedInput(inputId) {
    let inputElement = document.getElementById(inputId);

    // Устанавливаем фокус в начало строки при фокусе на поле ввода
    inputElement.addEventListener('click', function () {
      selectText(inputElement);
    });

    MaskedInput({
      elm: inputElement,
      format: '+7(___)-___-__-__',
      separator: '+7()-'
    });
  }

  // Функция для выделения всего текста в поле ввода
  function selectText(input) {
    input.setSelectionRange(0, input.value.length);
  }
</script>