Project_Dj_hnzlru/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls', namespace='home')),
    path('authorization/', include('authorization.urls', namespace='authorization')),
    path('patients/', include('patients.urls', namespace='patients')),

    # TODO: сделать редирект на 404
    # Перенаправление всех несуществующих URL на главную страницу
    path('<path:invalid_path>', RedirectView.as_view(url='/', permanent=False)),
]

home/urls.py
from django.urls import path, include
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', HomeListView.as_view(), name='index'),
    path('client_questions/', ClientQuestions.as_view(), name='client_questions'),
    path('client_results/', ClientResults.as_view(), name='client_results'),

    path('send_email_health_check/', send_email_health_check, name='send_email_health_check'),
    path('notification/<code>', notification, name='notification'),
]

patients/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView

from patients import views
from patients.views import *


app_name = 'patients'

urlpatterns = [
    path('all/', login_required(BrowseListView.as_view()), {'page': 1}, name='browse'),
    path('all/<int:page>/', login_required(BrowseListView.as_view()), name='browse'),


    path('dispensary/', login_required(DispensaryListView.as_view()), {'page': 1}, name='dispensary'),
    path('dispensary/<int:page>/', login_required(DispensaryListView.as_view()), name='dispensary'),

    path('search/', search, name='search'),
    path('add/', add, name='add'),

    path('patients/edit/<int:patient_id>/', views.edit, name='edit'),
    path('patients/delete/<int:patient_id>/', views.delete, name='delete'),
]

patients/models.py
from datetime import date
from django.db import models

from patients.models_choices import *


class COPDPatients(models.Model):
    class Meta:
        db_table = 'COPD_patients'
        verbose_name = "пациента"
        verbose_name_plural = "Пациенты ХОБЛ"

    # 1 - номер - это ID по умолчанию

    # 2.1 - имя
    name = models.CharField(max_length=20)

    # 2.2 - отчество
    surname = models.CharField(max_length=30)

    # 2.3 - фамилия
    patronymic = models.CharField(max_length=30)

    # 3 - дата рождения
    # birthday = models.DateField()
    birthday = models.CharField(max_length=30)

    # 4 - возраст
    age = models.PositiveSmallIntegerField(default=0)

    # 5 - адрес
    address = models.CharField(max_length=150)

    # **

    # 6 - МО прикрепления
    medical_organization_attachments = models.CharField(max_length=200)

    # 7 - Год установления диагноза	ХОБЛ
    year_of_diagnosis_of_COPD = models.DateField(default=date.today)

    # 8 - Инвалидность
    disability = models.BooleanField(default=False)

    # 9 - Госпитализации в течении 12 мес с кодом по МКБ
    hospitalization_with_year_with_ICD = models.CharField(max_length=30)

    # 10 - Количество обращений по поводу ХОБЛ за год
    requests_number_COPD = models.PositiveSmallIntegerField(default=0)

    # 11 - Количество обращений по поводу ХОБЛ за год - по поводу обострений
    requests_number_COPD_with_aggravation = models.PositiveSmallIntegerField(default=0)

    # 12 - Лечение амбулаторных обострений
    outpatient_exacerbations = models.CharField(max_length=20)

    # 13 - Вакцинация против (гриппа, пневмококка)
    vaccination = models.CharField(
        max_length=1,
        choices=VACCINATION_CHOICES,
        default=1,
    )

    # 14 - ОФВ/ФЖЕЛ после бронходилатации
    FEV_FVC_after_bronchodilation = models.CharField(max_length=10)

    # 15 - ОФВ1 после бронходилатации
    OFV1_after_bronchodilation = models.CharField(max_length=200)

    # 16 - Эозинофилы крови кл/мкл
    blood_eosinophils = models.FloatField(default=1.0)

    # 17 - Сатурация
    saturation = models.PositiveSmallIntegerField(default=0)

    # 18 - mMRC
    m_MRC = models.PositiveSmallIntegerField(choices=M_MRC_CHOICES, default=1)


    # 19 - Коротко действующие бронходилататоры, кол-во ингаляторов год
    salbutamol = models.CharField(
        max_length=1,
        choices=SALBUTAMOL_CHOICES,
        default=1,
    )

    # 20 - ДДБА/ДДАХП
    DDBA_DDAHP = models.CharField(
        max_length=1,
        choices=DDBA_DDAHP_CHOICES,
        default=5,
    )

    # 21 - ИГКС/ДДБА указать МНН
    IGCS_DDBA = models.CharField(
        max_length=1,
        choices=IGCS_DDBA_CHOICES,
        default=1,
    )

    # 22 - ДДАХП
    DDAHP = models.CharField(
        max_length=1,
        choices=DDAHP_CHOICES,
        default=1,
    )

    # 23 - Тройные фиксированные комбинации
    triple_fixed_combinations = models.CharField(
        max_length=1,
        choices=TRIPLE_FIXED_COMBINATIONS_CHOICES,
        default=1,
    )

    # 24 - посев мокроты: результат микробиологического анализа
    sputum_sowing = models.CharField(max_length=200)


    # 25 - сопутствующие заболевания: код МКБ
    ICD = models.PositiveSmallIntegerField(default=0)


    # 26 - Дата поступления на учет
    consists_under_DN = models.DateField()

    # 27 - Исход заболевания за год
    diseases_per_year = models.CharField(
        max_length=1,
        choices=DISEASES_PER_YEAR_CHOICES,
        default=1,
    )

    # 28 - Непосредственная причина смерти
    cause_of_death = models.TextField()

    # **

    # 29 - Диспансерное наблюдение с датой (это статус)
    # выбыл / переехал / умер
    dispensary_observation_status = models.CharField(
        max_length=1,
        choices=DISPENSARY_OBSERVATION_STATUS,
        default=1,
    )

    dispensary_observation_date_status = models.DateField()

    def __str__(self):
        return f"id: {self.id} | ФИО: {self.name}"

patients/views.py
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
from patients.forms import PatientAddForm, PatientEditForm
from patients.models import COPDPatients
from django.contrib import messages
from patients.models_choices import DISPENSARY_OBSERVATION_STATUS


class PatientsListView(ListView):
    model = COPDPatients
    context_object_name = 'COPDPatients'
    paginate_by = 10
    template_name = 'patients/browse.html'

    current_date = datetime.now().date()
    date_ago = current_date - timedelta(days=6*30)

    def get_queryset(self):
        """get_queryset родительского класса"""
        queryset = super(PatientsListView, self).get_queryset()
        return queryset

    def get_dispensary_patients_count(self, dispensary=False):
        dispensary_counts = {}

        for key, val in DISPENSARY_OBSERVATION_STATUS:
            queryset = self.model.objects.filter(dispensary_observation_status=key)

            if dispensary:
                queryset = queryset.filter(
                    dispensary_observation_date_status__lt=self.date_ago,
                    dispensary_observation_status=key
                )

            dispensary_counts[val] = queryset.count()

        return dispensary_counts

    # аналогично выражению ниже
    # current_date = datetime.now().date()
    # date_ago = current_date - timedelta(days=6*30)
    # patients = COPDPatients.objects.filter(dispensary_observation_date_status__lt=date_ago)
    def get_alert_dispensary_patients(self):
        patients = self.get_queryset()
        dispensary_alert = False

        for patient in patients:
            # Получаем разницу между текущей датой и датой наблюдения пациента
            difference = self.current_date - patient.dispensary_observation_date_status

            # Если хотя бы у одного пациента разница больше 6 месяцев...
            if difference > timedelta(days=6*30):
                dispensary_alert = True
                break

        return dispensary_alert


class BrowseListView(PatientsListView):
    def get_context_data(self, **kwargs):
        context = super(BrowseListView, self).get_context_data()

        current_site = self.request.get_host()
        breadcrumb_data = [
            {'label': current_site, 'url': current_site},
            {'label': 'Пациенты', 'url': '#'},
        ]

        # **

        context['breadcrumb_data'] = breadcrumb_data
        context['patients_count'] = self.get_queryset().count()
        context['patients_dispensary'] = self.get_dispensary_patients_count()
        context['dispensary_alert'] = self.get_alert_dispensary_patients()
        return context


class DispensaryListView(PatientsListView):
    def get_queryset(self):
        """get_queryset перегруженный в классе DispensaryListView"""
        queryset = super(DispensaryListView, self).get_queryset()
        return queryset.filter(dispensary_observation_date_status__lt=self.date_ago)

    def get_context_data(self, **kwargs):
        context = super(DispensaryListView, self).get_context_data()

        current_site = self.request.get_host()
        breadcrumb_data = [
            {'label': current_site, 'url': current_site},
            {'label': 'Диспансеризация', 'url': '#'},
        ]

        # **

        context['breadcrumb_data'] = breadcrumb_data
        context['patients_count'] = self.get_queryset().count()
        context['patients_dispensary'] = self.get_dispensary_patients_count(True)
        context['dispensary_alert'] = self.get_alert_dispensary_patients()
        return context


@login_required()
def search(request):
    current_site = request.get_host()

    breadcrumb_data = [
        {'label': current_site, 'url': current_site},
        {'label': 'Поиск', 'url': '#'},
    ]

    # **

    query = request.GET.get('patients_search', '')

    if query:
        results = COPDPatients.objects.filter(Q(patronymic__icontains=query) | Q(name__icontains=query))
    else:
        return HttpResponseRedirect(reverse('patients:browse'))

    context = {
        'breadcrumb_data': breadcrumb_data,
        'COPDPatients': results,
        'patients_dispensary': results.count(),
        'current_url': request.path,
    }

    return render(request, 'patients/browse.html', context)


@login_required
def add(request):
    current_site = request.get_host()

    breadcrumb_data = [
        {'label': current_site, 'url': current_site},
        {'label': 'Пациенты', 'url': HttpResponseRedirect(reverse('patients:browse'))},
        {'label': 'Добавить', 'url': '#'},
    ]

    # **

    if request.method == 'POST':
        form = PatientAddForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Пациент успешно добавлен в БД')

            return HttpResponseRedirect(reverse('patients:browse'))

    else:
        form = PatientAddForm()

    # **

    context = {
        'form': form,
        'breadcrumb_data': breadcrumb_data,
        'add_url': reverse('patients:add')
    }

    return render(request, 'patients/add_edit.html', context)


@login_required
def edit(request, patient_id):
    # Получите данные пациента по ID из базы данных
    patient = COPDPatients.objects.get(pk=patient_id)

    current_site = request.get_host()

    breadcrumb_data = [
        {'label': current_site, 'url': current_site},
        {'label': 'Пациенты', 'url': HttpResponseRedirect(reverse('patients:browse'))},
        {'label': f'Редактирование ID: {patient_id} ({patient.patronymic} {patient.name} {patient.surname})', 'url': '#'},
    ]

    # **

    if request.method == 'POST':

        # Передайте данные пациента в форму для редактирования
        form = PatientEditForm(request.POST, instance=patient)

        if form.is_valid():
            form.save()

            messages.info(
                request,
                f'ID: {patient_id} ('
                f'{patient.patronymic} {patient.name} {patient.surname}'
                f') - изменен')

            return HttpResponseRedirect(reverse('patients:browse'))
    else:
        form = PatientEditForm(instance=patient)

    # **

    context = {
        'form': form,
        'breadcrumb_data': breadcrumb_data,
        'patient': patient,
    }

    return render(request, 'patients/add_edit.html', context)


@login_required
def delete(request, patient_id):
    patient = COPDPatients.objects.get(id=patient_id)
    patient.delete()

    messages.warning(
        request,
        f'ID: {patient_id} ('
        f'{patient.patronymic} {patient.name} {patient.surname}'
        f') - успешно удален')

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

patients/templates/patients/browse.html
{% extends 'patients/layout.html' %}
{% block title %}Список внесенных пациентов{% endblock %}

{% block content %}
  <section id="page-content" class="no-sidebar">
    <div class="container">

      <!-- оповещение -->
      {% if messages %}
        {% for message in messages %}
          <div class="col-lg-6">
            <div role="alert"
               class="alert

               {% if message.tags == 'success' %}
                  alert-success
               {% elif message.tags == 'info' %}
                  alert-info
               {% elif message.tags == 'warning' %}
                  alert-warning
               {% endif %}

               alert-dismissible"
            >
              <button type="button"
                      class="btn-close"
                      data-bs-dismiss="alert"
                      aria-label="Close"> </button>

              <strong>
                <i class="fa fa-check-circle"></i> Успешно!
              </strong> {{ message }}
            </div>
          </div>
        {% endfor %}
      {% endif %}

      <div class="row mb-5">

        <div class="col-lg-6">
          <h4>Список пациентов ХОБЛ / ХНЗЛ</h4>
          <p>
            Всего пациентов: <b>{{ patients_count }}</b>, из них:<br>
              {% for key, val in patients_dispensary.items %}
                {{ key }}: <b>{{ val }}</b>;
              {% endfor %}
          <p>
        </div>

        <form class="col-lg-6 patients__search-form float-right"
              action="{% url 'patients:search' %}"
              method="get"
        >
          <input class="form-control patients__search-input col-lg-6 text-end"
                 name="patients_search"
                 type="text"
                 placeholder="Введите Фамилию или Имя для поиска..."
          >
          <span class="text-muted col-lg-6 text-end">
            Введите запрос &amp; нажмите Enter для поиска
          </span>
        </form>

        <div class="row">
          <!-- control_buttons: begin -->
          <div class="col-lg-12">
            <div class="col-lg-6 text-end float-right">
              <a href="{% url 'patients:add' %}" class="btn btn-light"><i class="icon-plus"></i> Добавить пациента</a>

              <div class="p-dropdown ml-3 float-right">
                <a class="title btn btn-light"><i class="icon-sliders"></i> Опции</a>

                <div class="p-dropdown-content">
                  <ul>
                    {% if user.is_superuser %}
                      <li><a href="{% url "admin:index" %}" target="_blank"><i class="icon-sliders"></i>Админ панель</a></li>
                      <li><hr class="space"></li>
                    {% endif %}

                    <li><a href="{% url "patients:browse" page=1 %}"><i class="icon-refresh-cw"></i>Обновить БД</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <!-- control_buttons: end -->

          <!-- patients_list: begin -->
          <table id="datatable" class="table table-bordered table-hover" style="width:100%">
            <thead>
              <tr>
                <th><b>ID</b></th>
                <th><b>ФИО</b></th> <!-- 2 -->
                <th><b>Дата рождения</b></th> <!-- 3 -->
                <th><b>Возраст</b></th> <!-- 4 -->

                <th><b>Обращений</b></th> <!-- 10 -->
                <th><b>Вакцинация</b></th> <!-- 13 -->
                <th><b>Инвалидность</b></th> <!-- 8 -->

                <th><b>Статус</b></th> <!-- 29 -->
                <th><b>Действия</b></th>
              </tr>
            </thead>

            <tbody>
              {% for patient in COPDPatients %}
                <tr>
                  <td>{{ patient.id }}</td>
                  <td>{{ patient.patronymic }} {{ patient.name }} {{ patient.surname }}</td>
                  <td>{{ patient.birthday }}</td>
                  <td>{{ patient.age }}</td>
                  <td>{{ patient.requests_number_COPD }}</td>
                  <td>{{ patient.get_vaccination_display }}</td>
                  <td>{% if patient.disability %}Да{% else %}Нет{% endif %}</td>

                  <td>
                    {# bg-primary#}
                    {# bg-secondary#}
                    {# bg-danger#}
                    {# bg-info#}
                    {# bg-warning#}
                    {# bg-success#}

                    <span class="badge badge-pill
                        {% if patient.dispensary_observation_status == "1" %}
                          bg-warning
                        {% elif patient.dispensary_observation_status == "2" %}
                          bg-success
                        {% elif patient.dispensary_observation_status == "3" %}
                          bg-danger
                        {% endif %}
                    ">
                      {{ patient.get_dispensary_observation_status_display }}
                    </span>
                  </td>

                  <!-- control buttons: begin -->
                  <td>
                    <a class="ms-2 text-reset"
                       href="{% url "patients:edit" patient.id %}"
                       data-bs-toggle="tooltip"
                       data-bs-original-title="Редактировать"
                    >
                      <i class="icon-edit"></i>
                    </a>

                    <a class="ms-2 text-reset"
                       id="patient-view"
                       href=""
                       data-bs-target="#modal-{{ patient.id }}"
                       data-bs-toggle="modal"
                       data-bs-original-title="Просмотр"
                    >
                      <i class="icon-eye"></i>
                    </a>

                    {% if user.is_superuser %}
                      <a class="ms-2 text-reset"
                         href="{% url "patients:delete" patient.id %}"
                         data-bs-toggle="tooltip"
                         data-bs-original-title="Удалить"
                      >
                        <i class="icon-trash-2"></i>
                      </a>
                    {% endif %}
                    <!-- control buttons: end -->
                  </td>
                </tr>

                <!-- modal pre-view for current patient: begin -->
                {% include 'patients/template_fast_view.html' with patient=patient %}
                <!-- modal pre-view for current patient: end -->
              {% endfor %}
            </tbody>
          </table>
          <!-- patients_list: end -->

          <!-- paginator: begin -->
          {% if is_paginated %}
            <nav>
              <ul class="pagination justify-content-center">

                <!-- назад -->
                <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                  <a class="page-link"
                    href=" {% if page_obj.has_previous %}{% url 'patients:browse' page_obj.previous_page_number %}{% else %}#{% endif %}"
                    tabindex="-1" aria-disabled="true"
                  >
                    <i class="fa fa-angle-left"></i>
                  </a>
                </li>

                {% if page_obj.number > 3 %}
                  <!-- всегда первая страница -->
                  <li class="page-item">
                    <a class="page-link" href="{% url 'patients:browse' 1 %}">1</a>
                  </li>

                  <!-- прочие страницы -->
                  <li class="page-item disabled">
                    <span class="page-link">...</span>
                  </li>
                {% endif %}

                <!-- перебираем все страницы пагинации -->
                {% for page in page_obj.paginator.page_range %}
                  <!-- текущая стр > текущая стр - 3 И текущ стр < текущ стр + 3, ТО... -->
                  {% if page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                    <li class="page-item {% if page == page_obj.number %} active {% endif %}">
                      <a class="page-link" href="{% url 'patients:browse' page %}">
                        {{ page }}
                      </a>
                    </li>
                  {% endif %}
                {% endfor %}

                {% if page_obj.paginator.num_pages > page_obj.number|add:'3' %}
                  <!-- прочие страницы -->
                  <li class="page-item disabled">
                    <span class="page-link">...</span>
                  </li>

                  <!-- всегда последняя страница -->
                  <li class="page-item">
                    <a class="page-link" href="{% url 'patients:browse' page_obj.paginator.num_pages %}">
                      {{ page_obj.paginator.num_pages }}
                    </a>
                  </li>
                {% endif %}

                <!-- вперед -->
                <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                  <a class="page-link" href="{% if page_obj.has_next %}{% url 'patients:browse' page_obj.next_page_number %}{% else %}#{% endif %}">
                    <i class="fa fa-angle-right"></i>
                  </a>
                </li>

              </ul>
          </nav>
          {% endif %}
          <!-- paginator: end -->

        </div>
      </div>

    </div>
  </section>
{% endblock %}

patients/templates/patients/template_fast_view.html
<div class="modal" id="modal-{{ patient.id }}" tabindex="-1" role="modal" aria-labelledby="modal-label-{{ patient.id }}" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 id="modal-label-{{ patient.id }}" class="modal-title">
          ID: {{ patient.id }}
        </h4>
        <button aria-hidden="true" data-bs-dismiss="modal" class="btn-close modal__btn-close" type="button">×</button>
      </div>
      <div class="modal-body">
        <div class="row mb20">
          <div class="col-md-12">
            <p>Сводка о пациенте:</p>
            <p>ФИО: {{ patient.patronymic }} {{ patient.name }} {{ patient.surname }}</p>
            <p>Адрес: {{ patient.address }}</p>
            <p>Возраст: {{ patient.age }}</p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 xs-box">
            <div class="box-services-a">
              <h3>Данные пациента</h3>
              <p>Инвалидность: {% if patient.disability %}Да{% else %}Нет{% endif %}</p>
              <p>Статус: {{ patient.get_dispensary_observation_status_display }}</p>
              <p>Дата дисп. набл.: {{ patient.dispensary_observation_date_status }}</p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="box-services-a">
              <h3>Медицинские данные</h3>
              <p>Адрес: {{ patient.medical_organization_attachments }}</p>
              <p>Год диагноза: {{ patient.year_of_diagnosis_of_COPD }}</p>
              <p>Вакцинация: {{ patient.get_vaccination_display }}</p>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button data-bs-dismiss="modal" class="btn btn-b" type="button">Закрыть</button>
      </div>
    </div>
  </div>
</div>